spring.application.name=spring-boot
spring.datasource.url = jdbc:postgresql://localhost:5332/golam
spring.datasource.username = golam
spring.datasource.password = golam123
spring.datasource.driver-class-name = org.postgresql.Driver

spring.jpa.hibernate.ddl-auto = create-drop
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.show-sql = true
